# Generated by Django 5.0.3 on 2024-03-16 08:16

import core.apps.junatics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junatics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junatics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.apps.junatics.models.user_directory_path, verbose_name='Product Image:'),
        ),
    ]
