# Generated by Django 5.0.3 on 2024-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junatics', '0002_alter_junatics_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='junatics',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
