# Generated by Django 5.0.3 on 2024-03-16 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junatics', '0003_junatics_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junatics',
            options={'verbose_name': 'Junatics', 'verbose_name_plural': 'Junatics'},
        ),
        migrations.AddField(
            model_name='junatics',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
